// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {guestexec} from '../models';
import {context} from '../models';

export function GuestRun(arg1:guestexec.RunRequest):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
