// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';

export function JobCancel(arg1:string):Promise<void>;

export function JobDismiss(arg1:string):Promise<void>;

export function JobGet(arg1:string):Promise<jobs.Job>;

export function JobList():Promise<Array<jobs.Job>>;
