// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JobCancel(arg1) {
  return window['go']['jobs']['API']['JobCancel'](arg1);
}

export function JobDismiss(arg1) {
  return window['go']['jobs']['API']['JobDismiss'](arg1);
}

export function JobGet(arg1) {
  return window['go']['jobs']['API']['JobGet'](arg1);
}

export function JobList() {
  return window['go']['jobs']['API']['JobList']();
}
