// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jobs} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<jobs.Job|boolean>;

export function JobCancel(arg1:string):Promise<void>;

export function JobGet(arg1:string):Promise<jobs.Job>;

export function JobList():Promise<Array<jobs.Job>>;

export function List():Promise<Array<jobs.Job>>;

export function Submit(arg1:string,arg2:string,arg3:any):Promise<string>;
