// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['jobs']['Manager']['Cancel'](arg1);
}

export function Get(arg1) {
  return window['go']['jobs']['Manager']['Get'](arg1);
}

export function JobCancel(arg1) {
  return window['go']['jobs']['Manager']['JobCancel'](arg1);
}

export function JobDismiss(arg1) {
  return window['go']['jobs']['Manager']['JobDismiss'](arg1);
}

export function JobGet(arg1) {
  return window['go']['jobs']['Manager']['JobGet'](arg1);
}

export function JobList() {
  return window['go']['jobs']['Manager']['JobList']();
}

export function List() {
  return window['go']['jobs']['Manager']['List']();
}

export function SetContext(arg1) {
  return window['go']['jobs']['Manager']['SetContext'](arg1);
}

export function Submit(arg1, arg2, arg3) {
  return window['go']['jobs']['Manager']['Submit'](arg1, arg2, arg3);
}
