// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InventoryDatastores() {
  return window['go']['inventory']['Binding']['InventoryDatastores']();
}

export function InventoryHosts() {
  return window['go']['inventory']['Binding']['InventoryHosts']();
}

export function SetContext(arg1) {
  return window['go']['inventory']['Binding']['SetContext'](arg1);
}
