// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inventory} from '../models';
import {context} from '../models';

export function InventoryDatastores():Promise<Array<inventory.DatastoreInfo>>;

export function InventoryHosts():Promise<Array<inventory.HostInfo>>;

export function SetContext(arg1:context.Context):Promise<void>;
