// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeploySSHKey(arg1) {
  return window['go']['manager']['API']['DeploySSHKey'](arg1);
}

export function Download(arg1) {
  return window['go']['manager']['API']['Download'](arg1);
}

export function GuestRun(arg1) {
  return window['go']['manager']['API']['GuestRun'](arg1);
}

export function InventoryDatastores() {
  return window['go']['manager']['API']['InventoryDatastores']();
}

export function InventoryHosts() {
  return window['go']['manager']['API']['InventoryHosts']();
}

export function InventoryNetworks() {
  return window['go']['manager']['API']['InventoryNetworks']();
}

export function SSHDownload(arg1) {
  return window['go']['manager']['API']['SSHDownload'](arg1);
}

export function SSHRun(arg1) {
  return window['go']['manager']['API']['SSHRun'](arg1);
}

export function SSHUpload(arg1) {
  return window['go']['manager']['API']['SSHUpload'](arg1);
}

export function SnapshotCreate(arg1) {
  return window['go']['manager']['API']['SnapshotCreate'](arg1);
}

export function SnapshotDelete(arg1, arg2) {
  return window['go']['manager']['API']['SnapshotDelete'](arg1, arg2);
}

export function SnapshotList(arg1) {
  return window['go']['manager']['API']['SnapshotList'](arg1);
}

export function SnapshotRevert(arg1) {
  return window['go']['manager']['API']['SnapshotRevert'](arg1);
}

export function Upload(arg1) {
  return window['go']['manager']['API']['Upload'](arg1);
}

export function VMConsoleInfo(arg1) {
  return window['go']['manager']['API']['VMConsoleInfo'](arg1);
}

export function VMGet(arg1) {
  return window['go']['manager']['API']['VMGet'](arg1);
}

export function VMInstallTools(arg1) {
  return window['go']['manager']['API']['VMInstallTools'](arg1);
}

export function VMList() {
  return window['go']['manager']['API']['VMList']();
}

export function VMNetworkOptions(arg1) {
  return window['go']['manager']['API']['VMNetworkOptions'](arg1);
}

export function VMPowerOff(arg1) {
  return window['go']['manager']['API']['VMPowerOff'](arg1);
}

export function VMPowerOn(arg1) {
  return window['go']['manager']['API']['VMPowerOn'](arg1);
}

export function VMReset(arg1) {
  return window['go']['manager']['API']['VMReset'](arg1);
}

export function VMSuspend(arg1) {
  return window['go']['manager']['API']['VMSuspend'](arg1);
}

export function VMUpdateConfig(arg1) {
  return window['go']['manager']['API']['VMUpdateConfig'](arg1);
}

export function VMUpdateNetwork(arg1) {
  return window['go']['manager']['API']['VMUpdateNetwork'](arg1);
}
