// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';
import {manager} from '../models';

export function ConnectionInfo():Promise<config.ConnectionInfo>;

export function Disconnect(arg1:context.Context):Promise<void>;

export function Download(arg1:manager.DownloadRequest):Promise<string>;

export function GuestRun(arg1:manager.RunRequest):Promise<string>;

export function Install(arg1:manager.InstallRequest):Promise<string>;

export function InventoryDatastores():Promise<Array<manager.DatastoreInfo>>;

export function InventoryHosts():Promise<Array<manager.HostInfo>>;

export function InventoryNetworks():Promise<manager.NetworkSummary>;

export function SSHDownload(arg1:manager.SSHTransferRequest):Promise<string>;

export function SSHInstall(arg1:manager.SSHInstallRequest):Promise<string>;

export function SSHRun(arg1:manager.SSHRunRequest):Promise<string>;

export function SSHUpload(arg1:manager.SSHTransferRequest):Promise<string>;

export function SetBackend(arg1:manager.Backend):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SnapshotCreate(arg1:manager.CreateSnapshotRequest):Promise<string>;

export function SnapshotDelete(arg1:string,arg2:boolean):Promise<string>;

export function SnapshotList(arg1:string):Promise<Array<manager.SnapshotInfo>>;

export function SnapshotRevert(arg1:string):Promise<string>;

export function Upload(arg1:manager.UploadRequest):Promise<string>;

export function VMInstallTools(arg1:string):Promise<string>;

export function VMList():Promise<Array<manager.VMInfo>>;

export function VMPowerOff(arg1:string):Promise<string>;

export function VMPowerOn(arg1:string):Promise<string>;

export function VMReset(arg1:string):Promise<string>;

export function VMSuspend(arg1:string):Promise<string>;
