// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionInfo() {
  return window['go']['manager']['Manager']['ConnectionInfo']();
}

export function DeploySSHKey(arg1) {
  return window['go']['manager']['Manager']['DeploySSHKey'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['manager']['Manager']['Disconnect'](arg1);
}

export function Download(arg1) {
  return window['go']['manager']['Manager']['Download'](arg1);
}

export function GuestRun(arg1) {
  return window['go']['manager']['Manager']['GuestRun'](arg1);
}

export function Install(arg1) {
  return window['go']['manager']['Manager']['Install'](arg1);
}

export function InventoryDatastores() {
  return window['go']['manager']['Manager']['InventoryDatastores']();
}

export function InventoryHosts() {
  return window['go']['manager']['Manager']['InventoryHosts']();
}

export function InventoryNetworks() {
  return window['go']['manager']['Manager']['InventoryNetworks']();
}

export function ReplaceBackend(arg1, arg2) {
  return window['go']['manager']['Manager']['ReplaceBackend'](arg1, arg2);
}

export function SSHDownload(arg1) {
  return window['go']['manager']['Manager']['SSHDownload'](arg1);
}

export function SSHInstall(arg1) {
  return window['go']['manager']['Manager']['SSHInstall'](arg1);
}

export function SSHRun(arg1) {
  return window['go']['manager']['Manager']['SSHRun'](arg1);
}

export function SSHUpload(arg1) {
  return window['go']['manager']['Manager']['SSHUpload'](arg1);
}

export function SetContext(arg1) {
  return window['go']['manager']['Manager']['SetContext'](arg1);
}

export function SnapshotCreate(arg1) {
  return window['go']['manager']['Manager']['SnapshotCreate'](arg1);
}

export function SnapshotDelete(arg1, arg2) {
  return window['go']['manager']['Manager']['SnapshotDelete'](arg1, arg2);
}

export function SnapshotList(arg1) {
  return window['go']['manager']['Manager']['SnapshotList'](arg1);
}

export function SnapshotRevert(arg1) {
  return window['go']['manager']['Manager']['SnapshotRevert'](arg1);
}

export function Upload(arg1) {
  return window['go']['manager']['Manager']['Upload'](arg1);
}

export function VMGet(arg1) {
  return window['go']['manager']['Manager']['VMGet'](arg1);
}

export function VMInstallTools(arg1) {
  return window['go']['manager']['Manager']['VMInstallTools'](arg1);
}

export function VMList() {
  return window['go']['manager']['Manager']['VMList']();
}

export function VMPowerOff(arg1) {
  return window['go']['manager']['Manager']['VMPowerOff'](arg1);
}

export function VMPowerOn(arg1) {
  return window['go']['manager']['Manager']['VMPowerOn'](arg1);
}

export function VMReset(arg1) {
  return window['go']['manager']['Manager']['VMReset'](arg1);
}

export function VMSuspend(arg1) {
  return window['go']['manager']['Manager']['VMSuspend'](arg1);
}
