// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {vminfo} from '../models';

export function SetContext(arg1:context.Context):Promise<void>;

export function VMList():Promise<Array<vminfo.VMInfo>>;

export function VMPowerOff(arg1:string):Promise<void>;

export function VMPowerOn(arg1:string):Promise<void>;

export function VMReset(arg1:string):Promise<void>;

export function VMSuspend(arg1:string):Promise<void>;
