// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['vminfo']['Binding']['SetContext'](arg1);
}

export function VMList() {
  return window['go']['vminfo']['Binding']['VMList']();
}

export function VMPowerOff(arg1) {
  return window['go']['vminfo']['Binding']['VMPowerOff'](arg1);
}

export function VMPowerOn(arg1) {
  return window['go']['vminfo']['Binding']['VMPowerOn'](arg1);
}

export function VMReset(arg1) {
  return window['go']['vminfo']['Binding']['VMReset'](arg1);
}

export function VMSuspend(arg1) {
  return window['go']['vminfo']['Binding']['VMSuspend'](arg1);
}
