// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['snapshots']['Binding']['SetContext'](arg1);
}

export function SnapshotCreate(arg1) {
  return window['go']['snapshots']['Binding']['SnapshotCreate'](arg1);
}

export function SnapshotDelete(arg1, arg2) {
  return window['go']['snapshots']['Binding']['SnapshotDelete'](arg1, arg2);
}

export function SnapshotList(arg1) {
  return window['go']['snapshots']['Binding']['SnapshotList'](arg1);
}

export function SnapshotRevert(arg1) {
  return window['go']['snapshots']['Binding']['SnapshotRevert'](arg1);
}
