// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {snapshots} from '../models';

export function SetContext(arg1:context.Context):Promise<void>;

export function SnapshotCreate(arg1:snapshots.CreateRequest):Promise<string>;

export function SnapshotDelete(arg1:string,arg2:boolean):Promise<string>;

export function SnapshotList(arg1:string):Promise<Array<snapshots.SnapshotInfo>>;

export function SnapshotRevert(arg1:string):Promise<string>;
