// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ClearConnectionSettings(arg1:string):Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ConnectionStatus():Promise<string>;

export function Disconnect():Promise<void>;

export function LoadConnectionSettings():Promise<config.ConnectionSettings>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveConnectionSettings(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;
