// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ClearConnectionSettings():Promise<void>;

export function Connect(arg1:config.ConnectRequest):Promise<config.ConnectionInfo>;

export function ConnectionInfo():Promise<config.ConnectionInfo>;

export function Disconnect():Promise<void>;

export function LoadConnectionSettings():Promise<config.ConnectRequest>;

export function LoadCredential(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveConnectionSettings(arg1:config.ConnectRequest):Promise<void>;

export function SaveCredential(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;
