// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConnectionSettings() {
  return window['go']['main']['App']['ClearConnectionSettings']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectionInfo() {
  return window['go']['main']['App']['ConnectionInfo']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function LoadConnectionSettings() {
  return window['go']['main']['App']['LoadConnectionSettings']();
}

export function LoadCredential(arg1) {
  return window['go']['main']['App']['LoadCredential'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function SaveConnectionSettings(arg1) {
  return window['go']['main']['App']['SaveConnectionSettings'](arg1);
}

export function SaveCredential(arg1, arg2) {
  return window['go']['main']['App']['SaveCredential'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}
