// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {packetcapture} from '../models';

export function SetContext(arg1:context.Context):Promise<void>;

export function StartCapture(arg1:packetcapture.CaptureRequest):Promise<string>;
