// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['packetcapture']['Binding']['SetContext'](arg1);
}

export function StartCapture(arg1) {
  return window['go']['packetcapture']['Binding']['StartCapture'](arg1);
}
