// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filetransfer} from '../models';
import {context} from '../models';

export function Download(arg1:filetransfer.DownloadRequest):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Upload(arg1:filetransfer.UploadRequest):Promise<string>;
