// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['filetransfer']['Binding']['Download'](arg1);
}

export function SetContext(arg1) {
  return window['go']['filetransfer']['Binding']['SetContext'](arg1);
}

export function Upload(arg1) {
  return window['go']['filetransfer']['Binding']['Upload'](arg1);
}
